CREATE TABLE customers (
FirstName VARCHAR(20),
LastName VARCHAR(20),
ID INTEGER NOT NULL,
PhoneNumber INTEGER NOT NULL,
Email VARCHAR(100),
OrderNumber INTEGER,

PRIMARY KEY (ID) 
);

USE PIZZA;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD OrderDetails VARCHAR(100);

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
RENAME COLUMN OrderNumber TO OrderID;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
RENAME COLUMN ID TO PersonID;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
RENAME COLUMN PersonID TO CustomerID;

SELECT * FROM CUSTOMERS;

CREATE TABLE ORDERS (
OrderID INT NOT NULL,
OrderDetails VARCHAR(100),
CustomerID INT NOT NULL,

PRIMARY KEY (OrderID),
FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
DROP COLUMN OrderID;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS
DROP COLUMN OrderDetails;

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS
VALUES ('John', 'Smith', 1, 0123456789, 'johnsmith@gmail.com');

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS (FirstName, LastName, CustomerID, PhoneNumber, Email)
VALUES ('Jane', 'Smith', 2, 0123456789, 'janesmith@gmail.com');

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;

SELECT * FROM ORDERS;

UPDATE CUSTOMERS C
SET C.PhoneNumber = 111111111
WHERE C.FirstName = 'john';

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;

DELETE FROM ORDERS
WHERE ORDERS.OrderID = 101;

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
ADD COLUMN (
OrderDate INT NOT NULL,
OrderTime INT NOT NULL,

CONSTRAINT POrderDateTime PRIMARY KEY (OrderDate, OrderTime)
);

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
DROP COLUMN OrderDate;

ALTER TABLE ORDERS
DROP COLUMN OrderTime;

SELECT * FROM ORDERS;

ALTER TABLE ORDERS
ADD COLUMN (
OrderDate INT NOT NULL,
OrderTime INT NOT NULL,

CONSTRAINT PK_OrderDateTime PRIMARY KEY (OrderDate, OrderTime)
);

SELECT * FROM ORDERS;

SELECT * FROM CUSTOMERS;

ALTER TABLE ORDERS
ADD CONSTRAINT FK_CustomerID
FOREIGN KEY (CustomerID)
REFERENCES CUSTOMERS(CustomerID);

SELECT * FROM ORDERS;

